# Generated by Django 5.0.3 on 2025-04-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0002_create_default_manager'),
        ('smartlib_api', '0019_book_book_file_alter_book_book_image_and_more'),
    ]

    operations = [
    ]
